config/routes.rb
Rails.application.routes.draw do

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root "posts#index"

  resources :users

  resources :posts do

    resources :tags, only: [:create, :destroy]

  end

  resources :comments, only: [:create, :destroy]

  get "posts/create" => "posts#new"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_many :tags, through: :post_tags

	scope :has_comments, -> do
		posts = Post.all
		posts.select{ |post| post.comments.count > 0 }
	end

	scope :allows_comments, -> { where(comments_on: true) }
end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
	belongs_to :post
	belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments

	scope :leora, -> { where(username: "leora") }

	scope :frequent_user, -> do 
		users = User.all

		users.select{ |user| user.posts.count > 3 }
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  # def current_user
  #   @_current_user ||= session[:current_user_id] &&
  #     User.find_by(id: session[:current_user_id])
  # end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	current_user
    @comment = Comment.new(comment_params)
    @comment.save
    redirect_to post_path(@comment.post_id)
  end

  def destroy
  	@comment = Comment.find(params[:id])
  	# @post_id = @comment.post_id
  	@comment.destroy
    # redirect_to post_path(@post_id)
  end

  private

  def comment_params
  	params.require(:comment).permit(:body, :user_id, :post_id)
  end

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  
  def create
  	if user = User.authenticate(params[:username], params[:password])
      session[:current_user_id] = user.id
      redirect_to root_url
    end
  end

  def destroy
    @_current_user = session[:current_user_id] = nil
    redirect_to root_url
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  # def current_user
  #   if session[:user_id]
  #     @current_user = User.find(session[:user_id])
  #   end
  # end

  def index
    @posts = Post.all.reverse
  end

  def show
    current_user
    @post = Post.find(params[:id])
    # @user = User.where(id: @post.user_id)
    @user = @post.user
    @comments = Comment.where(post_id: params[:id])
    @comment = Comment.new
  end

  def create
    current_user
    # @user = User.find(77)
    # ^ temp hardcoding until login/sessions working
    @post = Post.new(post_params)
      # title: params[:post][:title], body: params[:post][:body], post_tags_id: params[:post][:post_tags_id], user_id: @user.id
    @post.comments_on = true
    @post.save
    redirect_to post_path(@post)
  end

  def new
    current_user
    @post = Post.new
    @comment = Comment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :post_tags_id, :user_id, :comments_on)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(username: params[:session][:username].downcase)
    if user && user.password == (params[:session][:password])
    	log_in user
    	redirect_to user
		else
			flash.now[:danger] = "Something isn't right...check your username and password again."
  		render 'new'
  	end
  end

  def destroy
  	log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def create
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all.reverse
  end

  def show
    current_user
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id).reverse
    @tags = Tag.all
  end

  def create
    @user = User.new(user_params)
    @user.save
    if @user.save
      log_in @user
      redirect_to @user
      flash[:success] = "Welcome aboard, blog-friend!"
    else
      render 'new'
    end
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to posts_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :email, :firstname, :lastname, :age)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper

	# def user_display
	# 	content_tag :p, class: "username", do link_to post.user.username, user_path(post.user), :style=>'text-decoration: none; color: blue' end
	# end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snoop Bloggy Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <!-- ^ this line is giving an error with the .coffee script files: SyntaxError: [stdin]:3:19: reserved word 'function' -->
  <%= csrf_meta_tags %>
</head>
<body>

<% if logged_in? %>
  <h3>You're signed in as <span class="signature"><%= link_to @current_user.username, user_path(@current_user), :style=>'text-decoration: none; color: blue' %></span></h3>
	<%= link_to "Sign Out", logout_path, method: :delete %>
<% else %>
	Sign In:
	<%= form_for :session, url: login_path do |f| %>
	<%=f.label "Username" %>
	<%=f.text_field :username %><br>
	<%=f.label "Password" %>
	<%=f.password_field :password %><br>
	<%=f.submit "Sign In" %>
	<% end %><br>
	<%= link_to "Click Here to Sign Up", new_user_path %><br>
<% end %>

<div class="banner-box">
	<h1 class="banner"><a href="/posts">Snoop Bloggy Blog</a></h1>
</div>

<%= yield %>

</body>
</html>

app/views/logins/new.html.erb
<h1>Logins#create</h1>
<p>Find me in app/views/logins/create.html.erb</p>

app/views/posts/edit.html.erb
<h1 class="subheader">Edit Your Post:</h1>

<%= form_for @post do |f| %>
<%=f.label "Bloggy Title" %>
<%=f.text_field :title %><br><br>
<%=f.label "Bloggy Body" %>
<%=f.text_area :body, size: "100x10" %><br><br>
<%=f.label "Bloggy Tags" %>
<%=f.text_field :post_tags_id %>
<%=f.hidden_field :user_id, :value => @post.user.id %>
<%=f.submit %>
<% end %>

<%= button_to "Delete This Post", post_path(@post), method: :delete %><br>

<%= link_to "Return to Post", post_path(@post) %><br>
<%= link_to "Return to the Bloggy Blog Feed", posts_path %>

app/views/posts/index.html.erb
<%= link_to "Click Here to Bloggy Blog", new_post_path %><br>
<%= link_to "Click Here to See the Users List", users_path %><br>

<h1 class="subheader">Here's what's happening on Snoop Bloggy Blog:</h1>

<% @posts.each do |post| %>

	<h1 class="post-title"><%= link_to post.title, post_path(post), :style=>'text-decoration: none; color: red' %></h1>
	<%= post.body %><br>
	By  
		<% if post.user %>
			<span class="signature"><%= link_to post.user.username, user_path(post.user), :style=>'text-decoration: none; color: blue' %></span><br>
		<% else %>
			<span class="signature">User Deleted</span><br>
		<% end %>
		<span class="post-date">Posted: <%= post.created_at %></span><br><br>
	<hr>

<% end %>

app/views/posts/new.html.erb
<% if logged_in? %>

<h1 class="subheader">Feeling Bloggy? Blog about it:</h1>

<%= form_for @post do |f| %>
<%=f.label "Bloggy Title" %>
<%=f.text_field :title %>
<br>
<br>
<%=f.label "Bloggy Body" %>
<%=f.text_area :body, size: "100x10" %>
<br>
<br>
<%=f.label "Bloggy Tags" %>
<%=f.text_field :post_tags_id %>
<%=f.label "Allow comments?" %>
<%=f.check_box :comments_on, :checked => true %>
<br>
<br>
<%=f.hidden_field :user_id, :value => @current_user.id %>
<%=f.submit %>
<% end %>

<% else %>

<h1 class="subheader">Whoa there -- you need to sign in first!</h1>

<% end %>

app/views/posts/show.html.erb
<div class="post-title"><%= @post.title %></div>

	<p class="post-body"><%= @post.body %></p>
	<br>
	By: <span class="signature"><%= link_to @user.username, user_path(@user), :style=>'text-decoration: none; color: blue' %></span><br>

	<hr>

<h3>Comments:</h3>

		<!-- Feed of all current comments, chronological -->
<div class="comment-list">
	<% @comments.each do |comment| %>
		<div class="comment">
			<%= comment.body %>
			<br>
			By  
				<% if comment.user %>
					<span class="signature"><%= link_to comment.user.username, user_path(comment.user), :style=>'text-decoration: none; color: blue' %></span>
					<br>
				<% else %>
					<span class="signature">User Deleted</span>
					<br>
				<% end %> 
				<span class="post-date">Posted: <%= comment.created_at %></span>
				<br>
				<br>
				<% if comment.user == current_user %>
					<%= link_to "Delete Comment", comment_path(comment), method: :delete, remote: true, class: "delete-comment" %>
				<% else %>
				<% end %>
			<hr>
		</div>
	<% end %>
</div>

<!-- form for new comments -->

<% if logged_in? && @post.comments_on %>

<%= form_for @comment do |f| %>
<%=f.label "Comment:" %>
<%=f.text_field :body %>
<br>
<br>
<%=f.hidden_field :user_id, :value => @current_user.id %>
<%=f.hidden_field :post_id, :value => @post.id %>
<%=f.submit %>
<% end %>

<hr>

<% else %>
<% end %>

<!-- links -->
<% if logged_in? && @user.id == @current_user.id %>
<%= link_to "Edit This Post", edit_post_path(@post) %>
<% else %>
<% end %>
<br>
<%= link_to "Blog About Something", new_post_path %>
<br>
<%= link_to "Return to the Bloggy Blog Feed", posts_path %>

app/views/users/edit.html.erb
<h1 class="subheader">Edit Your User Info:</h1>

<div class="username"><%= @user.username %></div>
<%= form_for @user do |f| %>
<%=f.label "Password" %>
<%=f.password_field :password %><br>
<%=f.label "Email" %>
<%=f.text_field :email %><br>
<%=f.label "First Name" %>
<%=f.text_field :firstname %><br>
<%=f.label "Last Name" %>
<%=f.text_field :lastname %><br>
<%=f.label "Age" %>
<%=f.number_field :age %><br>
<%=f.submit %>
<% end %>

<%= button_to "DELETE YOUR ACCOUNT FOREVER", user_path(@user), method: :delete %>
<br>
<%= link_to "Return to Profile", user_path(@user) %>

app/views/users/index.html.erb
<h1 class="subheader">All of these wonderful people are using Snoop Bloggy Blog:</h1>

<ul>
<% @users.each do |user| %>

	<li><%= link_to user.username, user_path(user) %></li>

<% end %>
</ul>

app/views/users/new.html.erb
<h1 class="subheader">Welcome, intrepid blogger-person!  Please tell us things:</h1>

<%= form_for @user do |f| %>
<%=f.label "Pick a username" %>
<%=f.text_field :username %><br>
<%=f.label "Password" %>
<%=f.password_field :password %><br>
<%=f.label "Email" %>
<%=f.text_field :email %><br>
<%=f.label "First Name" %>
<%=f.text_field :firstname %><br>
<%=f.label "Last Name" %>
<%=f.text_field :lastname %><br>
<%=f.label "Age" %>
<%=f.number_field :age %><br>
<%=f.submit %>
<% end %>

app/views/users/show.html.erb
<hr>
<div class="username"><%= @user.username %></div>

Name: <%= @user.firstname %> <%= @user.lastname %><br>
Email: <%= @user.email %><br>
Age: <%= @user.age %><br>

<% if logged_in? && @user.id == @current_user.id %>
<%= link_to "Edit Your Profile", edit_user_path %>
<br>
<%= link_to "Click Here to Bloggy Blog", new_post_path %>
<% else %>
<% end %>

<hr>

<div class="subheader">My Bloggy Blogs:</div>

<% @posts.each do |post| %>

	<div class="post-title"><%= link_to post.title, post_path(post), :style=>'text-decoration: none; color: red' %></div><br>
	<%= post.body %><br><br>
	<!-- <div class="post-tag"><%= post.post_tags_id %></div><br> -->
	<span class="post-date">Posted: <%= post.created_at %></span><br><br>

<% end %>

<hr>

<%= link_to "Return to Users List", users_path %>
<br>
<%= link_to "Check Out the Bloggy Blog Feed", posts_path %>
<br>
<% if logged_in? && @user.id == @current_user.id %>
<%= link_to "DELETE YOUR ACCOUNT FOREVER", user_path(@user.id), method: :delete %>
<% else %>
<% end %>